#import <UIKit/UIKit.h>
#import "Gigya.h"

@class GSPluginView;

/**
 This protocol defines methods that can be implemented to handle <GSPluginView> events. All methods are optional.
 */
@protocol GSPluginViewDelegate <NSObject>

@optional

/**
 Invoked after a plugin view has finished loading a plugin.
 
 @param pluginView The plugin view that has finished loading.
 @param event A dictionary containing details of the event, with fields as described in the relevant plugin's documentation.
 */
- (void)pluginView:(GSPluginView *)pluginView finishedLoadingPluginWithEvent:(NSDictionary *)event;

/**
 Invoked when the plugin fires a [custom event](http://developers.gigya.com/010_Developer_Guide/84_Using_the_Client_API/50_Events#Component_events). (For example - commentUI's [commentSubmitted](http://developers.gigya.com/020_Client_API/030_Comments/comments.showCommentsUI#onCommentSubmitted_Event_Data))
 
 @param pluginView The plugin view that has fired the event.
 @param event The event object.
 */
- (void)pluginView:(GSPluginView *)pluginView firedEvent:(NSDictionary *)event;

/**
 Invoked after encountering an error, either generated by the plugin or while loading.
 
 @param pluginView The plugin view that has encountered the error.
 @param error An error object specifying the specific error.
 */
- (void)pluginView:(GSPluginView *)pluginView didFailWithError:(NSError *)error;

@end

/** `GSPluginView` is a custom UIView that renders Gigya [JS Plugins](http://developers.gigya.com/010_Developer_Guide/18_Plugins) and integrates them seamlessly with the Gigya iOS SDK.
 
 `GSPluginView` currently supports the following plugins:

 | Plugin                                                                                                    | Full Name            |
 |-----------------------------------------------------------------------------------------------------------|----------------------|
 | [Comments](http://developers.gigya.com/010_Developer_Guide/18_Plugins/022_Comments_Version_2)             | comments.commentsUI  |
 | [Reviews](http://developers.gigya.com/010_Developer_Guide/18_Plugins/025_Rating_Reviews)                  | comments.commentsUI  |
 | [RaaS Screen-Sets](http://developers.gigya.com/010_Developer_Guide/10_UM360/040_Raas/030_Markup)          | accounts.screenSet   |


 Example - adding a `GSPluginView` to a `UIViewController`:
 
    GSPluginView *pluginView = [[GSPluginView alloc] initWithFrame:CGRectMake(0, 0, 320, 200)];
    pluginView.delegate = self;
    [pluginView loadPlugin:@"comments.commentsUI" parameters:params];
    [self.view addSubview:pluginView];
 
 */
@interface GSPluginView : UIView

/** @name Setting the Delegate */

/*!
 The delegate object that receives plugin events.
 
 @see GSPluginViewDelegate
 */
@property (nonatomic, assign) id<GSPluginViewDelegate> delegate;

/** @name Loading a Plugin */

/*!
 Loads a plugin with the given name.
 
 @param plugin The plugin's name as described in the table above.
 */
- (void)loadPlugin:(NSString *)plugin;

/*!
 Loads a plugin with the given name and parameters.
 
 @param plugin The plugin's name as described in the table above.
 @param parameters The parameters passed to the plugin.
 */
- (void)loadPlugin:(NSString *)plugin parameters:(NSDictionary *)parameters;

/*!
 The name of the loaded plugin.
 */
@property (nonatomic, readonly) NSString *plugin;

/** @name Configuring Plugin Display */

/*!
 A Boolean value that specifies whether to show a progress indicator during a login process initiated from the plugin view.
 */
@property (nonatomic) BOOL showLoginProgress;

/*!
 Text to be displayed under the progress indicator during a login process initiated from the plugin view.
 */
@property (nonatomic, copy) NSString *loginProgressText;

/*!
 A Boolean value that specifies whether to show a progress indicator while the plugin is loaded.
 */
@property (nonatomic) BOOL showLoadingProgress;

/*!
 Text to be displayed under the progress indicator while the plugin is loaded.
 */
@property (nonatomic, copy) NSString *loadingProgressText;

@property (nonatomic) NSInteger javascriptLoadingTimeout;



@end
